package main

import (
	"encoding/base64"
	"net/url"
	"strings"
	"testing"
)

// TestSignRequestMatchesReferenceVector pins the signer to the exact canonical
// request and signature produced by the CodeArts Agent extension's own
// SDK-HMAC-SHA256 implementation. The expected values were generated by running
// that extracted implementation over the same inputs.
func TestSignRequestMatchesReferenceVector(t *testing.T) {
	const (
		wantSignature = "0093888a0805c8535df7212bd72024fea1570eabb927853f44a4d0827204bac4"
		wantSigned    = "content-type;plugin-name;x-domain-id;x-language;x-sdk-date;x-security-token"
		wantCanonical = "POST\n/api/v2/chat/completions/\n\n" +
			"content-type:application/json\n" +
			"plugin-name:snap_vscode\n" +
			"x-domain-id:dom\n" +
			"x-language:en-us\n" +
			"x-sdk-date:20260102T030405Z\n" +
			"x-security-token:tok\n" +
			"\n" + wantSigned + "\n" +
			"78b0e11c6754fc9671c2034f4a068d3a0e53c1c22a5a33900dd46bc8cd9136f3"
	)

	headers := map[string]string{
		"content-type":     "application/json",
		"X-Security-Token": "tok",
		"X-Domain-Id":      "dom",
		"plugin-name":      "snap_vscode",
		"X-Language":       "en-us",
		"X-Sdk-Date":       "20260102T030405Z",
	}
	cred := &credential{
		AccessKeyID:     "AKIDEXAMPLE",
		SecretAccessKey: "secret",
		SecurityToken:   "tok",
		DomainID:        "dom",
	}

	// Sign without injecting host so the header set matches the reference.
	signed, errSign := signRequest("POST",
		"https://snap-access.cn-north-4.myhuaweicloud.com/api/v2/chat/completions",
		headers, []byte(`{"model":"x"}`), cred, false)
	if errSign != nil {
		t.Fatalf("signRequest returned an error: %v", errSign)
	}

	authorization := signed[headerAuth]
	if !strings.Contains(authorization, "Signature="+wantSignature) {
		t.Fatalf("signature mismatch:\n got %q\nwant signature %q", authorization, wantSignature)
	}
	if !strings.Contains(authorization, "SignedHeaders="+wantSigned) {
		t.Fatalf("signed headers mismatch:\n got %q\nwant %q", authorization, wantSigned)
	}

	// Re-derive the canonical request to confirm the intermediate value too.
	canonical := strings.Join([]string{
		"POST",
		canonicalURI("/api/v2/chat/completions"),
		canonicalQueryString(url.Values{}),
		"content-type:application/json\n" +
			"plugin-name:snap_vscode\n" +
			"x-domain-id:dom\n" +
			"x-language:en-us\n" +
			"x-sdk-date:20260102T030405Z\n" +
			"x-security-token:tok\n",
		wantSigned,
		sha256Hex([]byte(`{"model":"x"}`)),
	}, "\n")
	if canonical != wantCanonical {
		t.Fatalf("canonical request mismatch:\n got %q\nwant %q", canonical, wantCanonical)
	}
}

func TestCanonicalURIEscapesSegmentsAndAddsTrailingSlash(t *testing.T) {
	cases := map[string]string{
		"/api/v2/chat/completions": "/api/v2/chat/completions/",
		"/v1/chat/chat":            "/v1/chat/chat/",
		"/a b/c":                   "/a%20b/c/",
		"/already/":                "/already/",
		"":                         "/",
	}
	for input, want := range cases {
		if got := canonicalURI(input); got != want {
			t.Errorf("canonicalURI(%q) = %q, want %q", input, got, want)
		}
	}
}

func TestCanonicalQueryStringSortsAndEscapes(t *testing.T) {
	values := url.Values{}
	values.Set("ticket_id", "abc-123")
	values.Set("secret", "a b/c")
	values.Add("multi", "z")
	values.Add("multi", "a")

	got := canonicalQueryString(values)
	want := "multi=a&multi=z&secret=a%20b%2Fc&ticket_id=abc-123"
	if got != want {
		t.Fatalf("canonicalQueryString = %q, want %q", got, want)
	}
}

func TestRequestCarriesBody(t *testing.T) {
	if !requestCarriesBody("POST") || !requestCarriesBody("put") {
		t.Fatal("POST and PUT must be treated as body bearing")
	}
	if requestCarriesBody("GET") || requestCarriesBody("DELETE") {
		t.Fatal("GET and DELETE must sign the empty-body digest")
	}
}

func TestSignRequestRejectsIncompleteCredential(t *testing.T) {
	_, errSign := signRequest("POST", "https://example.invalid/x", nil, nil, &credential{AccessKeyID: "only-ak"}, false)
	if errSign == nil {
		t.Fatal("expected an error for a credential without a secret key")
	}
}

// encodeBase64 is a small helper for the lifecycle tests, which must send
// config_yaml in the host's base64 form.
func encodeBase64(data []byte) string {
	return base64.StdEncoding.EncodeToString(data)
}
